config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/home', to: 'static_pages#home', as: 'static_pages_home'
  get 'static_pages/eshop', to: 'static_pages#eshop', as: 'static_pages_eshop'
  get 'static_pages/prestations', to: 'static_pages#prestations', as: 'static_pages_prestations'
  get 'static_pages/about', to: 'static_pages#about', as: 'static_pages_about'
  get 'static_pages/team', to: 'static_pages#team', as: 'static_pages_team'
  get 'eshop/eshop_index', to: 'eshop#eshop_index', as: 'eshop_index'
  get 'eshop/item/:id', to: 'eshop#show', as: 'eshop_item'
  get 'contacts/contact', to: 'contacts#contact', as: 'contacts_contact'

  resources :items, only: [:show] do
    post 'add_to_cart', on: :member
  end

  resource :cart, only: [:show] do
    member do
      put 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
      delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
    end
  end

  resources :orders, only: [:create, :show]

  resources :contacts

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#home'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  before_validation :calculate_total_price

  def calculate_total_price
    self.total_price = order_items.sum('quantity * unit_price')
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    @order = create_order(current_user, current_user.cart)

    if @order.persisted?
      redirect_to @order, notice: 'Order was successfully created.'
    else
      redirect_to cart_path(current_user.cart), alert: 'There was an error creating the order.'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def create_order(user, cart)
    order = nil

    Order.transaction do
      order = user.orders.create!

      cart.cart_items.each do |cart_item|
        order.order_items.create!(
          item: cart_item.item,
          quantity: cart_item.quantity,
          unit_price: cart_item.item.price
        )
      end

      # calculate_total_price will be called before validation
      # Save order to trigger before_validation callback
      order.save!

      # Clear the cart
      cart.cart_items.destroy_all
    end

    order
  rescue ActiveRecord::RecordInvalid => e
    # Handle errors and transaction rollback
    flash[:alert] = "There was an error creating the order: #{e.message}"
    nil
  end
end

app/views/orders/show.html.erb
<!DOCTYPE html>
<% content_for :title, "Commande" %>
<% content_for :meta_description, "Page d'accueil commande boutique ESPEREN" %>

<body>
  <section class="h-100 order-page">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12">
          <h1 class="fw-bold mb-0 text-black">Commande</h1>
          <h6 class="mb-0 text-muted">Commande n° <%= @order.id %></h6>
          <hr class="my-4">

          <!-- Loop through order items -->
          <% @order.order_items.each do |order_item| %>
            <div class="card mb-4">
              <div class="card-body">
                <div class="row g-0">
                  <div class="col-md-2 col-lg-2 col-xl-2">
                    <img src="<%= order_item.item.image_url %>" class="img-fluid rounded-3" alt="<%= order_item.item.title %>">
                  </div>
                  <div class="col-md-3 col-lg-3 col-xl-3">
                    <h6 class="text-black mb-0"><%= order_item.item.title %></h6>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                    <h6 class="mb-0">Quantité: <%= order_item.quantity %></h6>
                  </div>
                  <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                    <h6 class="mb-0">€ <%= order_item.unit_price %></h6>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <!-- End of loop -->

          <hr class="my-4">
          <div class="pt-5">
            <h6 class="mb-0">
              <%= link_to eshop_index_path, class: "text-body" do %>
                <i class="fas fa-long-arrow-alt-left me-2"></i>
                Retour à la boutique
              <% end %>
            </h6>
          </div>
        </div>
      </div>
      <!-- Afficher le montant total de la commande -->
      <div class="card ms-auto" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Total de la commande</h5>
          <p class="card-text">€ <%= @order.total_price %></p>
        </div>
      </div>
      <!-- Bouton paiement Stripe -->
        <div class="text-end ms-auto">
          <%= button_to "Procéder au paiement", checkout_create_path(total_price: @order.total_price), class: "btn btn-secondary", data: { turbo: false } %>
        </div>
    </div>
  </section>
</body>