config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/home', to: 'static_pages#home', as: 'static_pages_home'
  get 'static_pages/eshop', to: 'static_pages#eshop', as: 'static_pages_eshop'
  get 'static_pages/prestations', to: 'static_pages#prestations', as: 'static_pages_prestations'
  get 'static_pages/about', to: 'static_pages#about', as: 'static_pages_about'
  get 'static_pages/team', to: 'static_pages#team', as: 'static_pages_team'
  get 'eshop/eshop_index', to: 'eshop#eshop_index', as: 'eshop_index'
  get 'eshop/item/:id', to: 'eshop#show', as: 'eshop_item'
  get 'contacts/contact', to: 'contacts#contact', as: 'contacts_contact'

  resources :items, only: [:show] do
    post 'add_to_cart', on: :member
  end

  resource :cart, only: [:show] do
    member do
      put 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
      delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
    end
  end

  resources :orders, only: [:create, :show]

  resources :contacts

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#home'
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
  end

  def create
    # Récupérer les données du formulaire
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    reason = params[:reason]
    message = params[:message]
    file = params[:file]

    # Appeler le mailer pour envoyer l'email
    ContactMailer.contact_email({
      first_name: first_name,
      last_name: last_name,
      email: email,
      reason: reason,
      message: message,
      file: file
    }).deliver_now

    # Rediriger ou retourner une réponse selon vos besoins
    redirect_to root_path, notice: 'Votre message a été envoyé.'
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/contact.html.erb
<!DOCTYPE html>
<% content_for :title, "Contact" %>
<% content_for :meta_description, "Coordonnées ESPEREN" %>
<html>
<head>
  <!-- Inclusion des polices -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link href="https://db.onlinewebfonts.com/c/49ded67c36cc1c2fe20918442aa23902?family=Rondal+Regular" rel="stylesheet">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <!-- Inclusion du fichier CSS de Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Inclusion du fichier CSS personnalisé -->
  <%= stylesheet_link_tag 'custom_styles', 'data-turbo-track': 'reload' %>
</head>
<body>
<div class="container text-center mt-3">
  <h1>Nous contacter</h1>
</div>
<div class="container card-container mt-4">
  <div class="row">
    <div class="col-md-8">
      <div class="card p-4 h-100">
        <%= form_with(model: @contact, url: contacts_path, html: { multipart: true }, local: true) do |form| %>
          <div class="mb-3">
            <label for="first_name" class="form-label">Prénom</label>
            <%= form.text_field :first_name, class: "form-control", id: "first_name", placeholder: "Entrez votre prénom", required: true %>
            <div class="invalid-feedback">Merci d'entrer votre prénom.</div>
          </div>

          <div class="mb-3">
            <label for="last_name" class="form-label">Nom</label>
            <%= form.text_field :last_name, class: "form-control", id: "last_name", placeholder: "Entrez votre nom", required: true %>
            <div class="invalid-feedback">Merci d'entrer votre nom.</div>
          </div>

          <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <div class="input-group">
              <span class="input-group-text" id="inputGroupPrepend">@</span>
              <%= form.email_field :email, class: "form-control", id: "email", placeholder: "Entrez votre adresse email", aria: { describedby: "inputGroupPrepend" }, required: true %>
              <div class="invalid-feedback">Merci d'entrer une adresse email valide.</div>
            </div>
          </div>

          <div class="mb-3">
            <label for="reason" class="form-label">Pourquoi souhaitez-vous nous contacter?</label>
            <%= form.select :reason, ['Candidature', 'Demande d\'informations', 'Demande de devis'], {}, class: "form-select", id: "reason" %>
          </div>

          <div class="mb-3">
            <label for="message" class="form-label">Entrez votre message ici:</label>
            <%= form.text_area :message, class: "form-control", id: "message", rows: 5 %>
          </div>

          <div class="mb-3">
            <label for="file" class="form-label">Joindre un fichier:</label>
            <%= form.file_field :file, class: "form-control-file", id: "file" %>
          </div>

          <div class="mb-3 form-check">
            <%= form.check_box :terms, class: "form-check-input", id: "invalidCheck", required: true %>
            <label class="form-check-label" for="invalidCheck">Agree to terms and conditions</label>
            <div class="invalid-feedback">You must agree before submitting.</div>
          </div>

          <%= form.submit 'Envoi', class: 'btn btn-secondary', data: { disable_with: 'Envoi en cours...' } %>
        <% end %>
      </div>
    </div>

    <div class="col-md-4 d-flex">
      <div class="card flex-fill h-100">
        <%= image_tag 'photo_contact.png', class: 'card-img-top h-100 w-100', alt: 'Contact' %>
      </div>
    </div>
  </div>
</div>

<!-- Inclusion du fichier JavaScript de Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
</body>
</html>