config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/home', to: 'static_pages#home', as: 'static_pages_home'
  get 'static_pages/eshop', to: 'static_pages#eshop', as: 'static_pages_eshop'
  get 'static_pages/prestations', to: 'static_pages#prestations', as: 'static_pages_prestations'
  get 'static_pages/about', to: 'static_pages#about', as: 'static_pages_about'
  get 'static_pages/team', to: 'static_pages#team', as: 'static_pages_team'
  get 'eshop/eshop_index', to: 'eshop#eshop_index', as: 'eshop_index'
  get 'eshop/item/:id', to: 'eshop#show', as: 'eshop_item'
  get 'contacts/contact', to: 'contacts#contact', as: 'contacts_contact'

  resources :items, only: [:show] do
    post 'add_to_cart', on: :member
  end

  resource :cart, only: [:show] do
    member do
      put 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
      delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
    end
  end

  resources :orders, only: [:create, :show]

  resources :contacts

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#home'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items

  validates :user_id, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart
    @cart_items = current_user.cart.cart_items
    @total_price = @cart_items.sum { |cart_item| cart_item.item.price * cart_item.quantity }
  end

  def update_quantity
    @cart_item = current_user.cart.cart_items.find(params[:id])
    if @cart_item.update(quantity: params[:cart_item][:quantity])
      @total_price = current_user.cart.cart_items.sum { |cart_item| cart_item.item.price * cart_item.quantity }
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to cart_path, notice: 'Quantité mise à jour.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to cart_path, alert: 'Erreur de mise à jour.' }
      end
    end
  end

  def destroy_item
    @cart_item = current_user.cart.cart_items.find(params[:id])
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path, notice: 'Article supprimé du panier.' }
      format.js
    end
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<!DOCTYPE html>
<head>
  <% content_for :title, "Mon panier" %>
  <% content_for :meta_description, "Contenu du panier boutique ESPEREN" %>

  <script src="/assets/cart.js"></script>
</head>
<body>
  <section class="h-100 cart-page">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12">
          <h1 class="fw-bold mb-0 text-black">Panier</h1>
          <h6 class="mb-0 text-muted"><%= current_user.cart.cart_items.count %> articles</h6>
          <hr class="my-4">

          <!-- Loop through cart items -->
          <% current_user.cart.cart_items.each do |cart_item| %>
            <turbo-frame id="cart_item_<%= cart_item.id %>">
              <div class="card mb-4">
                <div class="card-body">
                  <div class="row g-0">
                    <div class="col-md-2 col-lg-2 col-xl-2">
                      <img src="<%= cart_item.item.image_url %>" class="img-fluid rounded-3" alt="<%= cart_item.item.title %>">
                    </div>
                    <div class="col-md-3 col-lg-3 col-xl-3">
                      <h6 class="text-black mb-0"><%= cart_item.item.title %></h6>
                    </div>
                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                      <%= form_with model: cart_item, url: update_quantity_cart_path(cart_item), method: :put, local: false do |f| %>
                        <button type="button" class="btn btn-link px-2" onclick="updateQuantity(<%= cart_item.id %>, 'decrement')">
                          <i class="fas fa-minus"></i>
                        </button>
                        <%= f.number_field :quantity, min: 0, class: "form-control form-control-sm", value: cart_item.quantity, onchange: "this.form.submit();" %>
                        <button type="button" class="btn btn-link px-2" onclick="updateQuantity(<%= cart_item.id %>, 'increment')">
                          <i class="fas fa-plus"></i>
                        </button>
                      <% end %>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                      <h6 class="mb-0">€ <%= cart_item.item.price %></h6>
                    </div>
                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                      <%= link_to 'Supprimer', destroy_item_cart_path(cart_item), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr ce vouloir supprimer cet article?" }, class: "text-muted delete-item" %>
                    </div>
                  </div>
                </div>
              </div>
            </turbo-frame>
          <% end %>
          <!-- End of loop -->

          <hr class="my-4">
          <!-- Affichage du montant total du panier -->
          <turbo-frame id="cart_total">
            <div class="card ms-auto" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">Total du panier</h5>
                <p class="card-text">€ <%= @total_price %></p>
              </div>
            </div>
          </turbo-frame>

          <!-- Ajout du bouton "Passer commande" -->
          <div class="text-end ms-auto">
            <%= form_with url: orders_path, method: :post do %>
              <%= submit_tag "Passer commande", class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script>
    function updateQuantity(cartItemId, action) {
      const input = document.querySelector(`#cart_item_${cartItemId} input[type='number']`);
      if (action === 'increment') {
        input.stepUp();
      } else if (action === 'decrement') {
        input.stepDown();
      }
      input.dispatchEvent(new Event('change'));
    }
  </script>
</body>

app/views/carts/update_quantity.turbo_stream.erb
<%= turbo_stream.replace "cart_item_#{@cart_item.id}" do %>
  <%= render @cart_item %>
<% end %>

<%= turbo_stream.replace "cart_total" do %>
  <div class="card ms-auto" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Total du panier</h5>
      <p class="card-text">€ <%= @total_price %></p>
    </div>
  </div>
<% end %>