config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'static_pages/home', to: 'static_pages#home', as: 'static_pages_home'
  get 'static_pages/eshop', to: 'static_pages#eshop', as: 'static_pages_eshop'
  get 'static_pages/prestations', to: 'static_pages#prestations', as: 'static_pages_prestations'
  get 'static_pages/about', to: 'static_pages#about', as: 'static_pages_about'
  get 'static_pages/team', to: 'static_pages#team', as: 'static_pages_team'
  get 'eshop/eshop_index', to: 'eshop#eshop_index', as: 'eshop_index'
  get 'eshop/item/:id', to: 'eshop#show', as: 'eshop_item'
  get 'contacts/contact', to: 'contacts#contact', as: 'contacts_contact'

  resources :items, only: [:show] do
    post 'add_to_cart', on: :member
  end

  resource :cart, only: [:show] do
    member do
      put 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
      delete 'destroy_item/:id', to: 'carts#destroy_item', as: 'destroy_item'
    end
  end

  resources :orders, only: [:create, :show]

  resources :contacts

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'static_pages#home'
end

app/controllers/eshop_controller.rb
class EshopController < ApplicationController
  before_action :authenticate_user!, only: [:add_to_cart]

def create
end

def eshop_index
  @items = Item.all
end

def eshop
end

def show
  @item = Item.find(params[:id])
  @related_items = Item.where.not(id: @item.id).limit(4) # Exclut l'item actuel et prend 4 items liés
end


end

app/views/eshop/add_to_cart.js.erb
document.getElementById('cart-count').textContent = "<%= current_user.cart.cart_items.sum(:quantity) %>";

app/views/eshop/eshop_index.html.erb
<!DOCTYPE html>
    <head>
        <% content_for :title, "Boutique" %>
        <% content_for :meta_description, "Boutique d'ESPEREN" %>

        <!-- Core theme CSS (includes Bootstrap)-->
        <style> 
        .background-light-grey {
        background-color: rgba(211, 211, 211, 0.8); /* Light grey with some transparency */
        padding: 20px;
        border-radius: 10px;
        }

        </style>
    </head>
    <body>
        <!-- Header-->
        <header class="bg-dark py-5"style="background-image: url('<%= asset_path('banniere_eshop.jpg') %>'); background-size: cover; background-position: center; background-repeat: no-repeat;">
             <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-dark background-light-grey"">
                    <h1 class="display-4 fw-bolder">Boutique Esperen</h1>
                    <p class="lead fw-normal text-dark-50 mb-0">Accessoires textiles confectionnés à l'atelier par nos couturièr⸱e⸱s</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <% @items.each do |item| %>
                    <div class="col mb-5">
                    <div class="card h-100">
                    <% if item.title == "Hello Camo" || item.title == "Yellow Wax Banana" %>
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Best Seller</div>
                    <% end %>
                     <!-- Product image-->
                    <img class="card-img-top" src="<%= asset_path(item.image_url) %>" alt="<%= item.title %>" />
                    <!-- Product details-->
                    <div class="card-body p-4">
                    <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder"><%= item.title %></h5>
                    <!-- Product description-->
                    <p><%= item.description %></p>
                     <!-- Product reviews (example, adjust as necessary)-->
                    <% if item.title == "Hello Camo" || item.title == "Yellow Wax Banana" %>
                    <div class="d-flex justify-content-center small text-warning mb-2">
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                    <div class="bi-star-fill"></div>
                  </div>
                <% end %>
                <!-- Product price-->
                <%= number_to_currency(item.price, unit: "€", format: "%n %u") %>
              </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="<%= eshop_item_path(item) %>">Voir en détail</a></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>

app/views/eshop/show.html.erb
<!DOCTYPE html>
<head>
  <% content_for :title, "Produit" %>
  <% content_for :meta_description, "Produit ESPEREN" %>
</head>
<body>
  <!-- Product section-->
  <section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
      <div class="row gx-4 gx-lg-5 align-items-center">
        <div class="col-md-6">
          <img class="card-img-top mb-5 mb-md-0" src="<%= asset_path(@item.image_url) %>" alt="<%= @item.title %>" />
        </div>
        <div class="col-md-6">
          <h1 class="display-5 fw-bolder"><%= @item.title %></h1>
          <div class="fs-5 mb-5">
            <span><%= number_to_currency(@item.price, unit: "€", format: "%n %u") %></span>
          </div>
          <p class="lead"><%= @item.description %></p>
          <div class="d-flex">
            <input class="form-control text-center me-3" id="inputQuantity" type="number" value="1" min="1" style="max-width: 3rem" />
             <% if user_signed_in? %>
              <%= button_to 'Ajouter au panier', add_to_cart_item_path(@item), method: :post, remote: true, class: 'btn btn-outline-dark flex-shrink-0' %>
            <% else %>
              <%= link_to 'Se connecter pour ajouter au panier', new_user_session_path, class: 'btn btn-outline-dark flex-shrink-0' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Related items section-->
  <section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
      <h2 class="fw-bolder mb-4">Related products</h2>
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <% @related_items.each do |related_item| %>
          <div class="col mb-5">
            <div class="card h-100">
              <!-- Product image-->
              <img class="card-img-top" src="<%= asset_path(related_item.image_url) %>" alt="<%= related_item.title %>" />
              <!-- Product details-->
              <div class="card-body p-4">
                <div class="text-center">
                  <!-- Product name-->
                  <h5 class="fw-bolder"><%= related_item.title %></h5>
                  <!-- Product price-->
                  <%= number_to_currency(related_item.price, unit: "€", format: "%n %u") %>
                </div>
              </div>
              <!-- Product actions-->
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="<%= eshop_item_path(related_item) %>">Voir en détail</a></div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>